### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by s390x** [jim11662418/wheelwriter-printer#1]
Thanks for the great work.
Are you able to list all the parts required for this project? The specific chips you used?
In particular, there are a few components on your perfboard that I do not recognize.
![schematic-annotated](https://user-images.githubusercontent.com/87795759/126591075-effcb127-c129-4402-89e9-ca67b2fd6dbd.jpg)

**Comment by jim11662418** [comment]
I apologize for not seeing your question earlier. The items to the left of the ICs are 0.1 uF capacitors connected to the Vcc and Gnd  pins of the ICs. The item to the right of the DS89C440 is a 12MHz crystal. Below that is a female mini-din connector for a PS/2 keyboard. Below that is a female 2.1mm barrel type connector for DC power. (Only used to power the MCU for testing when not connected to the Wheelwriter. DC power ordinarily comes from the Wheelwriter.). Below that is a 5 pin header for connecting the board to the Wheelwriter Printer Board.

**Comment by s390x** [comment]
Thank you!
