### ISSUE TITLE
Replacement for DS89C440 chip

### ISSUE THREAD

**Issue by edwardcw** [jim11662418/wheelwriter-printer#2]
Is there a recommended replacement chip as the DS89C440 is no longer available?

**Comment by jim11662418** [comment]
Either a DS89C420, DS89C430, DS89C440 or DS89C450 would work without any modifications for this project. They are no longer in production but there are a number of them (especially the DS89C420) available on [eBay](https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw=%28ds89c420%2Cds89c430%2Cds80c440%2Cds89c450%29&_sacat=0).  [Mouser](https://www.mouser.com/c/?q=ds89c430) has the DS89C430 in stock, although they're somewhat pricey compared to eBay. As an alternative, check out my project [here](https://github.com/jim11662418/wheelwriter-teletype). The IAP15W4K61S4 MCU is still in production.
